---
abstract: 'auto-create POD sections listing inherited methods'
author:
  - 'James Mastros, theorbtwo <james@mastros.biz>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Module::CoreList: 0
  Test::Differences: 0
  Test::EOL: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Inherit
no_index:
  directory:
    - inc
    - t
requires:
  Class::Load: 0
  List::AllUtils: 0
  MRO::Compat: 0
  Path::Class: 0
  Pod::POM: 0
  Sub::Identify: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
