--- #YAML:1.0
name:               Pod-Inherit
version:            0.04
abstract:           auto-create pod sections listing inherited methods
author:
    - James Mastros <james@mastros.biz>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MRO::Compat:          0
    Path::Class:          0
    Pod::Compiler:        0
    Sub::Identify:        0
    Test::Differences:    0
    Test::Exception:      0
    Test::More:           0
    Test::NoWarnings:     0
    Test::Pod:            0
    Test::Pod::Coverage:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
