---
abstract: 'auto-create pod sections listing inherited methods'
author:
  - 'James Mastros <james@mastros.biz>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Inherit
no_index:
  directory:
    - t
    - inc
requires:
  MRO::Compat: 0
  Module::CoreList: 0
  Path::Class: 0
  Pod::POM: 0
  Sub::Identify: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Warn: 0
version: 0.09
